RFQ/Presentation/SSG.Web/Administration/Models/Common/AddressModel.cs
using System.Collections.Generic;
using System.Web.Mvc;
using FluentValidation.Attributes;
using SSG.Admin.Validators.Common;
using SSG.Web.Framework;
using SSG.Web.Framework.Mvc;

namespace SSG.Admin.Models.Common
{
    [Validator(typeof(AddressValidator))]
    public partial class AddressModel : BaseSSGEntityModel
    {
        public AddressModel()
        {
            AvailableCountries = new List<SelectListItem>();
            AvailableStates = new List<SelectListItem>();
        }

        [SSGResourceDisplayName("Admin.Address.Fields.FirstName")]
        [AllowHtml]
        public string FirstName { get; set; }

        [SSGResourceDisplayName("Admin.Address.Fields.LastName")]
        [AllowHtml]
        public string LastName { get; set; }

        [SSGResourceDisplayName("Admin.Address.Fields.Email")]
        [AllowHtml]
        public string Email { get; set; }

        [SSGResourceDisplayName("Admin.Address.Fields.Company")]
        [AllowHtml]
        public string Company { get; set; }

        [SSGResourceDisplayName("Admin.Address.Fields.Country")]
        public int? CountryId { get; set; }

        [SSGResourceDisplayName("Admin.Address.Fields.Country")]
        [AllowHtml]
        public string CountryName { get; set; }

        [SSGResourceDisplayName("Admin.Address.Fields.StateProvince")]
        public int? StateProvinceId { get; set; }

        [SSGResourceDisplayName("Admin.Address.Fields.StateProvince")]
        [AllowHtml]
        public string StateProvinceName { get; set; }

        [SSGResourceDisplayName("Admin.Address.Fields.City")]
        [AllowHtml]
        public string City { get; set; }

        [SSGResourceDisplayName("Admin.Address.Fields.Address1")]
        [AllowHtml]
        public string Address1 { get; set; }

        [SSGResourceDisplayName("Admin.Address.Fields.Address2")]
        [AllowHtml]
        public string Address2 { get; set; }

        [SSGResourceDisplayName("Admin.Address.Fields.ZipPostalCode")]
        [AllowHtml]
        public string ZipPostalCode { get; set; }

        [SSGResourceDisplayName("Admin.Address.Fields.PhoneNumber")]
        [AllowHtml]
        public string PhoneNumber { get; set; }

        [SSGResourceDisplayName("Admin.Address.Fields.FaxNumber")]
        [AllowHtml]
        public string FaxNumber { get; set; }

        [SSGResourceDisplayName("Admin.Address")]
        public string AddressHtml { get; set; }



        public IList<SelectListItem> AvailableCountries { get; set; }
        public IList<SelectListItem> AvailableStates { get; set; }



        public bool FirstNameDisabled { get; set; }
        public bool LastNameDisabled { get; set; }
        public bool EmailDisabled { get; set; }
        public bool CompanyDisabled { get; set; }
        public bool CountryDisabled { get; set; }
        public bool StateProvinceDisabled { get; set; }
        public bool CityDisabled { get; set; }
        public bool Address1Disabled { get; set; }
        public bool Address2Disabled { get; set; }
        public bool ZipPostalCodeDisabled { get; set; }
        public bool PhoneNumberDisabled { get; set; }
        public bool FaxNumberDisabled { get; set; }
    }
}

RFQ/Presentation/SSG.Web/Administration/Models/Common/LanguageSelectorModel.cs
using System.Collections.Generic;
using SSG.Admin.Models.Localization;
using SSG.Web.Framework.Mvc;

namespace SSG.Admin.Models.Common
{
    public partial class LanguageSelectorModel : BaseSSGModel
    {
        public LanguageSelectorModel()
        {
            AvailableLanguages = new List<LanguageModel>();
        }

        public IList<LanguageModel> AvailableLanguages { get; set; }

        public LanguageModel CurrentLanguage { get; set; }
    }
}

RFQ/Presentation/SSG.Web/Administration/Models/Common/MaintenanceModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using SSG.Web.Framework;
using SSG.Web.Framework.Mvc;

namespace SSG.Admin.Models.Common
{
    public partial class MaintenanceModel : BaseSSGModel
    {
        public MaintenanceModel()
        {
            DeleteGuests = new DeleteGuestsModel();
            DeleteExportedFiles = new DeleteExportedFilesModel();
        }

        public DeleteGuestsModel DeleteGuests { get; set; }
        public DeleteExportedFilesModel DeleteExportedFiles { get; set; }

        #region Nested classes

        public partial class DeleteGuestsModel : BaseSSGModel
        {
            [SSGResourceDisplayName("Admin.System.Maintenance.DeleteGuests.StartDate")]
            [UIHint("DateNullable")]
            public DateTime? StartDate { get; set; }

            [SSGResourceDisplayName("Admin.System.Maintenance.DeleteGuests.EndDate")]
            [UIHint("DateNullable")]
            public DateTime? EndDate { get; set; }
            
            public int? NumberOfDeletedUsers { get; set; }
        }

        public partial class DeleteExportedFilesModel : BaseSSGModel
        {
            [SSGResourceDisplayName("Admin.System.Maintenance.DeleteExportedFiles.StartDate")]
            [UIHint("DateNullable")]
            public DateTime? StartDate { get; set; }

            [SSGResourceDisplayName("Admin.System.Maintenance.DeleteExportedFiles.EndDate")]
            [UIHint("DateNullable")]
            public DateTime? EndDate { get; set; }

            public int? NumberOfDeletedFiles { get; set; }
        }

        #endregion
    }
}

RFQ/Presentation/SSG.Web/Administration/Models/Common/SystemInfoModel.cs
using System;
using System.Collections.Generic;
using SSG.Web.Framework;
using SSG.Web.Framework.Mvc;

namespace SSG.Admin.Models.Common
{
    public partial class SystemInfoModel : BaseSSGModel
    {
        public SystemInfoModel()
        {
            this.LoadedAssemblies = new List<LoadedAssembly>();
        }

        [SSGResourceDisplayName("Admin.System.SystemInfo.ASPNETInfo")]
        public string AspNetInfo { get; set; }

        [SSGResourceDisplayName("Admin.System.SystemInfo.IsFullTrust")]
        public string IsFullTrust { get; set; }

        [SSGResourceDisplayName("Admin.System.SystemInfo.SSGVersion")]
        public string SSGVersion { get; set; }

        [SSGResourceDisplayName("Admin.System.SystemInfo.OperatingSystem")]
        public string OperatingSystem { get; set; }

        [SSGResourceDisplayName("Admin.System.SystemInfo.ServerLocalTime")]
        public DateTime ServerLocalTime { get; set; }

        [SSGResourceDisplayName("Admin.System.SystemInfo.ServerTimeZone")]
        public string ServerTimeZone { get; set; }

        [SSGResourceDisplayName("Admin.System.SystemInfo.UTCTime")]
        public DateTime UtcTime { get; set; }

        [SSGResourceDisplayName("Admin.System.SystemInfo.LoadedAssemblies")]
        public IList<LoadedAssembly> LoadedAssemblies { get; set; }

        public partial class LoadedAssembly : BaseSSGModel
        {
            public string FullName { get; set; }
            public string Location { get; set; }
        }

    }
}

RFQ/Presentation/SSG.Web/Administration/Models/Common/SystemWarningModel.cs
using SSG.Web.Framework.Mvc;

namespace SSG.Admin.Models.Common
{
    public partial class SystemWarningModel : BaseSSGModel
    {
        public SystemWarningLevel Level { get; set; }

        public string Text { get; set; }
    }

    public enum SystemWarningLevel
    {
        Pass,
        Warning,
        Fail
    }
}

RFQ/Presentation/SSG.Web/Administration/Controllers/CommonController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Security.Principal;
using System.Web.Mvc;
using SSG.Admin.Models.Common;
using SSG.Core;
using SSG.Core.Caching;
using SSG.Core.Domain.Directory;
using SSG.Core.Plugins;
using SSG.Services.Directory;
using SSG.Services.Helpers;
using SSG.Services.Localization;
using SSG.Services.Security;
using SSG.Services.Users;
using SSG.Web.Framework.Controllers;
using SSG.Web.Framework.Security;
using SSG.Core.Domain;

namespace SSG.Admin.Controllers
{
    [AdminAuthorize]
    public partial class CommonController : BaseSSGController
    {
        #region Fields

        private readonly ICurrencyService _currencyService;
        private readonly IMeasureService _measureService;
        private readonly IUserService _userService;
        private readonly IWebHelper _webHelper;
        private readonly SiteInformationSettings _siteInformationSettings;
        private readonly CurrencySettings _currencySettings;
        private readonly MeasureSettings _measureSettings;
        private readonly IDateTimeHelper _dateTimeHelper;
        private readonly ILanguageService _languageService;
        private readonly IWorkContext _workContext;
        private readonly IPermissionService _permissionService;
        private readonly ILocalizationService _localizationService;

        #endregion

        #region Constructors

        public CommonController(
            ICurrencyService currencyService, IMeasureService measureService,
            IUserService userService, IWebHelper webHelper,
            SiteInformationSettings siteInformationSettings, CurrencySettings currencySettings,
            MeasureSettings measureSettings, IDateTimeHelper dateTimeHelper,
            ILanguageService languageService, IWorkContext workContext,
            IPermissionService permissionService, ILocalizationService localizationService)
        {
            this._currencyService = currencyService;
            this._measureService = measureService;
            this._userService = userService;
            this._webHelper = webHelper;
            this._siteInformationSettings = siteInformationSettings;
            this._currencySettings = currencySettings;
            this._measureSettings = measureSettings;
            this._dateTimeHelper = dateTimeHelper;
            this._languageService = languageService;
            this._workContext = workContext;
            this._permissionService = permissionService;
            this._localizationService = localizationService;
        }

        #endregion

        #region Methods

        public ActionResult SystemInfo()
        {
            var model = new SystemInfoModel();
            model.SSGVersion = SSGVersion.CurrentVersion;
            try
            {
                model.OperatingSystem = Environment.OSVersion.VersionString;
            }
            catch (Exception) { }
            try
            {
                model.AspNetInfo = RuntimeEnvironment.GetSystemVersion();
            }
            catch (Exception) { }
            try
            {
                model.IsFullTrust = AppDomain.CurrentDomain.IsFullyTrusted.ToString();
            }
            catch (Exception) { }
            model.ServerTimeZone = TimeZone.CurrentTimeZone.StandardName;
            model.ServerLocalTime = DateTime.Now;
            model.UtcTime = DateTime.UtcNow;
            //Environment.GetEnvironmentVariable("USERNAME");
            foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                model.LoadedAssemblies.Add(new SystemInfoModel.LoadedAssembly()
                {
                    FullName =  assembly.FullName,
                    //we cannot use Location property in medium trust
                    //Location = assembly.Location
                });
            }
            return View(model);
        }

        public ActionResult Warnings()
        {
            var model = new List<SystemWarningModel>();

            //site URL
            if (!String.IsNullOrEmpty(_siteInformationSettings.SiteUrl) &&
                (_siteInformationSettings.SiteUrl.Equals(_webHelper.GetSiteLocation(false), StringComparison.InvariantCultureIgnoreCase)
                ||
                _siteInformationSettings.SiteUrl.Equals(_webHelper.GetSiteLocation(true), StringComparison.InvariantCultureIgnoreCase)
                ))
                model.Add(new SystemWarningModel()
                    {
                        Level = SystemWarningLevel.Pass,
                        Text = _localizationService.GetResource("Admin.System.Warnings.URL.Match")
                    });
            else
                model.Add(new SystemWarningModel()
                {
                    Level = SystemWarningLevel.Warning,
                    Text = string.Format(_localizationService.GetResource("Admin.System.Warnings.URL.NoMatch"), _siteInformationSettings.SiteUrl, _webHelper.GetSiteLocation(false))
                });


            //primary exchange rate currency
            var perCurrency = _currencyService.GetCurrencyById(_currencySettings.PrimaryExchangeRateCurrencyId);
            if (perCurrency != null)
            {
                model.Add(new SystemWarningModel()
                {
                    Level = SystemWarningLevel.Pass,
                    Text = _localizationService.GetResource("Admin.System.Warnings.ExchangeCurrency.Set"),
                });
                if (perCurrency.Rate != 1)
                {
                    model.Add(new SystemWarningModel()
                    {
                        Level = SystemWarningLevel.Fail,
                        Text = _localizationService.GetResource("Admin.System.Warnings.ExchangeCurrency.Rate1")
                    });
                }
            }
            else
            {
                model.Add(new SystemWarningModel()
                {
                    Level = SystemWarningLevel.Fail,
                    Text = _localizationService.GetResource("Admin.System.Warnings.ExchangeCurrency.NotSet")
                });
            }

            //primary site currency
            var pscCurrency = _currencyService.GetCurrencyById(_currencySettings.PrimarySiteCurrencyId);
            if (pscCurrency != null)
            {
                model.Add(new SystemWarningModel()
                {
                    Level = SystemWarningLevel.Pass,
                    Text = _localizationService.GetResource("Admin.System.Warnings.PrimaryCurrency.Set"),
                });
            }
            else
            {
                model.Add(new SystemWarningModel()
                {
                    Level = SystemWarningLevel.Fail,
                    Text = _localizationService.GetResource("Admin.System.Warnings.PrimaryCurrency.NotSet")
                });
            }


            //base measure weight
            var bWeight = _measureService.GetMeasureWeightById(_measureSettings.BaseWeightId);
            if (bWeight != null)
            {
                model.Add(new SystemWarningModel()
                {
                    Level = SystemWarningLevel.Pass,
                    Text = _localizationService.GetResource("Admin.System.Warnings.DefaultWeight.Set"),
                });

                if (bWeight.Ratio != 1)
                {
                    model.Add(new SystemWarningModel()
                    {
                        Level = SystemWarningLevel.Fail,
                        Text = _localizationService.GetResource("Admin.System.Warnings.DefaultWeight.Ratio1")
                    });
                }
            }
            else
            {
                model.Add(new SystemWarningModel()
                {
                    Level = SystemWarningLevel.Fail,
                    Text = _localizationService.GetResource("Admin.System.Warnings.DefaultWeight.NotSet")
                });
            }


            //base dimension weight
            var bDimension = _measureService.GetMeasureDimensionById(_measureSettings.BaseDimensionId);
            if (bDimension != null)
            {
                model.Add(new SystemWarningModel()
                {
                    Level = SystemWarningLevel.Pass,
                    Text = _localizationService.GetResource("Admin.System.Warnings.DefaultDimension.Set"),
                });

                if (bDimension.Ratio != 1)
                {
                    model.Add(new SystemWarningModel()
                    {
                        Level = SystemWarningLevel.Fail,
                        Text = _localizationService.GetResource("Admin.System.Warnings.DefaultDimension.Ratio1")
                    });
                }
            }
            else
            {
                model.Add(new SystemWarningModel()
                {
                    Level = SystemWarningLevel.Fail,
                    Text = _localizationService.GetResource("Admin.System.Warnings.DefaultDimension.NotSet")
                });
            }

            //incompatible plugins
            if (PluginManager.IncompatiblePlugins != null)
                foreach (var pluginName in PluginManager.IncompatiblePlugins)
                    model.Add(new SystemWarningModel()
                    {
                        Level = SystemWarningLevel.Warning,
                        Text = string.Format(_localizationService.GetResource("Admin.System.Warnings.IncompatiblePlugin"), pluginName )
                    });

            //validate write permissions (the same procedure like during installation)
            var dirPermissionsOk = true;
            var dirsToCheck = FilePermissionHelper.GetDirectoriesWrite(_webHelper);
            foreach (string dir in dirsToCheck)
                if (!FilePermissionHelper.CheckPermissions(dir, false, true, true, false))
                {

RFQ/Presentation/SSG.Web/Administration/Views/Common/LanguageSelector.cshtml
@model LanguageSelectorModel
@if (Model.AvailableLanguages.Count > 1)
{
    using (Ajax.BeginForm("LanguageSelected", "Common", null, new AjaxOptions { OnComplete = "onLanguageChangedRequestCompleted();" }, new { id = "form-languageselector" }))
    {
        var languages = Model.AvailableLanguages.Select(x => new SelectListItem
        {
            Text = x.Name,
            Value = x.Id.ToString(),
            Selected = x.Id.Equals(Model.CurrentLanguage.Id)
        });
    
        @Html.DropDownList("userlanguage", languages)
    }
    <script type="text/javascript">
        $(document).ready(function () {
            $("#userlanguage").change(onLanguageChanged);
        });

        function onLanguageChanged() {
            $("#form-languageselector").submit();
        }
        function onLanguageChangedRequestCompleted() {
            location.reload();
        }
    </script>
}

RFQ/Presentation/SSG.Web/Administration/Views/Common/Maintenance.cshtml
@model MaintenanceModel
@{
    //page title
    ViewBag.Title = @T("Admin.System.Maintenance").Text;
}
<div class="section-header">
    <div class="title">
        <img src="@Url.Content("~/Administration/Content/images/ico-system.png")" alt="" />
        @T("Admin.System.Maintenance")
    </div>
    <div class="options">
    </div>
</div>
@using (Html.BeginForm())
{
    <table width="100%">
        <tr>
            <td colspan="2">
                <strong>@T("Admin.System.Maintenance.DeleteGuests")</strong>
            </td>
        </tr>
        <tr>
            <td class="adminTitle">
                @Html.SSGLabelFor(model => model.DeleteGuests.StartDate):
            </td>
            <td class="adminData">
                @Html.EditorFor(model => model.DeleteGuests.StartDate)
            </td>
        </tr>
        <tr>
            <td class="adminTitle">
                @Html.SSGLabelFor(model => model.DeleteGuests.EndDate):
            </td>
            <td class="adminData">
                @Html.EditorFor(model => Model.DeleteGuests.EndDate)
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <input type="submit" name="delete-guests" class="t-button" value="@T("Admin.Common.Delete")" />
            </td>
        </tr>
        @if (Model.DeleteGuests.NumberOfDeletedUsers.HasValue)
        {
            <tr>
                <td colspan="2">
                    <strong>@string.Format(@T("Admin.System.Maintenance.DeleteGuests.TotalDeleted").Text, Model.DeleteGuests.NumberOfDeletedUsers.Value)</strong>
                </td>
            </tr>
        }
    </table>
    <p>
        <br />
        <hr />
        <br />
    </p>
    <table width="100%">
        <tr>
            <td colspan="2">
                <strong>@T("Admin.System.Maintenance.DeleteExportedFiles")</strong>
            </td>
        </tr>
        <tr>
            <td class="adminTitle">
                @Html.SSGLabelFor(model => model.DeleteExportedFiles.StartDate):
            </td>
            <td class="adminData">
                @Html.EditorFor(model => model.DeleteExportedFiles.StartDate)
            </td>
        </tr>
        <tr>
            <td class="adminTitle">
                @Html.SSGLabelFor(model => model.DeleteExportedFiles.EndDate):
            </td>
            <td class="adminData">
                @Html.EditorFor(model => Model.DeleteExportedFiles.EndDate)
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <input type="submit" name="delete-exported-files" class="t-button" value="@T("Admin.Common.Delete")" />
            </td>
        </tr>
        @if (Model.DeleteExportedFiles.NumberOfDeletedFiles.HasValue)
        {
            <tr>
                <td colspan="2">
                    <strong>@string.Format(@T("Admin.System.Maintenance.DeleteExportedFiles.TotalDeleted").Text, Model.DeleteExportedFiles.NumberOfDeletedFiles.Value)</strong>
                </td>
            </tr>
        }
    </table>
}

RFQ/Presentation/SSG.Web/Administration/Views/Common/SystemInfo.cshtml
@model SystemInfoModel
@{
    //page title
    ViewBag.Title = @T("Admin.System.SystemInfo").Text;
}
<div class="section-header">
    <div class="title">
        <img src="@Url.Content("~/Administration/Content/images/ico-system.png")" alt="" />
        @T("Admin.System.SystemInfo")
    </div>
</div>

<script type="text/javascript">
    function toggleAndChangeText() {
        $('#pnlLoadedAssemblies').toggle();
        if ($('#pnlLoadedAssemblies').css('display') == 'none') {
            $('#loadedAssembliesTag').html('@T("Admin.Common.Show")');
        }
        else {
            $('#loadedAssembliesTag').html('@T("Admin.Common.Hide")');
        }
    }
</script>
<table class="adminContent">
    <tr>
        <td class="adminTitle">
            @Html.SSGLabelFor(model => model.SSGVersion):
        </td>
        <td class="adminData">
            @Html.DisplayFor(model => model.SSGVersion)
        </td>
    </tr>
    <tr>
        <td class="adminTitle">
            @Html.SSGLabelFor(model => model.OperatingSystem):
        </td>
        <td class="adminData">
            @Html.DisplayFor(model => model.OperatingSystem)
        </td>
    </tr>
    <tr>
        <td class="adminTitle">
            @Html.SSGLabelFor(model => model.AspNetInfo):
        </td>
        <td class="adminData">
            @Html.DisplayFor(model => model.AspNetInfo)
        </td>
    </tr>
    <tr>
        <td class="adminTitle">
            @Html.SSGLabelFor(model => model.IsFullTrust):
        </td>
        <td class="adminData">
            @Html.DisplayFor(model => model.IsFullTrust)
        </td>
    </tr>
    <tr>
        <td class="adminTitle">
            @Html.SSGLabelFor(model => model.ServerTimeZone):
        </td>
        <td class="adminData">
            @Html.DisplayFor(model => model.ServerTimeZone)
        </td>
    </tr>
    <tr>
        <td class="adminTitle">
            @Html.SSGLabelFor(model => model.ServerLocalTime):
        </td>
        <td class="adminData">
            @Model.ServerLocalTime.ToString("F")
        </td>
    </tr>
    <tr>
        <td class="adminTitle">
            @Html.SSGLabelFor(model => model.UtcTime):
        </td>
        <td class="adminData">
            @Model.UtcTime.ToString("F")
        </td>
    </tr>
    <tr>
        <td class="adminTitle">
            @Html.SSGLabelFor(model => model.LoadedAssemblies):
        </td>
        <td class="adminData">
            <a id="loadedAssembliesTag" href="javascript:toggleAndChangeText();">@T("Admin.Common.Show")</a>
            <div id="pnlLoadedAssemblies" style="display:none">
                @foreach (var assembly in Model.LoadedAssemblies)
                {
                    @assembly.FullName
                    if (!String.IsNullOrEmpty(assembly.Location))
                    {
                        <br />
                        <em>@assembly.Location</em>
                    }
                    <br />
                }
            </div>
        </td>
    </tr>
</table>

RFQ/Presentation/SSG.Web/Administration/Views/Common/Warnings.cshtml
@model IList<SystemWarningModel>
@{
    //page title
    ViewBag.Title = @T("Admin.System.Warnings").Text;
}
<div class="section-header">
    <div class="title">
        <img src="@Url.Content("~/Administration/Content/images/ico-warnings.gif")" alt="" />
        @T("Admin.System.Warnings")
    </div>
</div>
<div class="system-warnings">
    <ul>
        @foreach (var warning in Model)
        {
            <li>
                @switch (warning.Level)
                {
                    case SystemWarningLevel.Pass:
                        {
                    <span class="pass">@warning.Text</span>
                        }
                        break;
                    case SystemWarningLevel.Warning:
                        {
                    <span class="warning">@warning.Text</span>
                        }
                        break;
                    case SystemWarningLevel.Fail:
                        {
                    <span class="fail">@warning.Text</span>
                        }
                        break;
                }
            </li>
        }
    </ul>
</div>